### ISSUE TITLE
Getting error when get in folder and refresh browser.

### ISSUE THREAD

**Issue by vanthao03596** [ctf0/Laravel-Media-Manager#94] opened 2019-05-07 08:06 UTC
> What version of Laravel are you using? (nothing lower than v5.4).

laravel 5.8

> is it an issue related to installation or usage ?

usage on development

> what is the error you are getting ?

I have folder name "Hello". When i click to this folder it work but when i refresh browser it show error.

> Extra Info "attaching a screen shot would be very helpful"

![image](https://user-images.githubusercontent.com/34786441/57283338-20156d00-70d9-11e9-9cb7-29f3c345e5ef.png)

> Do You Know A Solution For this Issue ?

I dont know this is the 1st time i try to using your package

**Comment by ctf0** [comment] 2019-05-07 18:56
ur issue is at this line
https://github.com/ctf0/Laravel-Media-Manager/blob/4b42464b14f0ee91bbb4e7b3fd12ef383a4d5337/src/resources/assets/js/modules/url.js#L13

sadly i cant test exactly what is the problem atm, but in the mean time you can play with and find the cause of the error

**Comment by vanthao03596** [comment] 2019-05-08 01:38
thanks for fast reply.

**Comment by xoxoj** [comment] 2019-05-09 05:59
@vanthao03596 what OS you using it?

**Comment by xoxoj** [comment] 2019-05-09 05:59
@vanthao03596 look like so cool...

**Comment by vanthao03596** [comment] 2019-05-09 06:59
@xoxoj I'm using manjaro kde.

**Comment by xoxoj** [comment] 2019-05-10 08:56
@vanthao03596 fedora?

**Comment by ctf0** [comment] 2019-05-17 09:05
will be fixed in next release

**Closed as completed by ctf0** 2019-05-17 09:05 UTC
Labels: bug
